# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14T3EQDcSX5FrCkvH7kIdAQQ-orCuigX3
"""

import pandas as pd

df1 = pd.read_excel('dados.xlsx',sheet_name='Por Canal')

df1

df2 = pd.read_excel('dados.xlsx', sheet_name='Consumo de Produtos')
df2

df2['T. Categoria'].isin(['DRINKS', 'SOFT DRINKS'])



df2

n_pessoas = df1.groupby('Estabelecimento')['N.Pessoas'].sum()
n_pessoas

quant = df2.groupby(['Estabelecimento','T. Categoria'])['Quant.'].sum()
quant

quat_por_pessoa = quant / n_pessoas
quat_por_pessoa

ax = quat_por_pessoa.plot.barh()
ax.bar_label(ax.containers[0], fmt='{:.2f}');
ax.set_xlim(0,ax.get_xlim()[1] * 1.1)

top5 = df2.groupby(['Estabelecimento', 'T. Categoria', 'Descrição'])['Quant.'].sum()
top5 = top5.sort_values(ascending=False)
top5 = top5.groupby(['Estabelecimento', 'T. Categoria']).head(5)
top5 = top5.sort_index()
top5

import matplotlib.pyplot as plt
import seaborn as sns

top5_df = top5.reset_index()

g = sns.catplot(
    data=top5_df,
    x='Quant.',
    y='Descrição',
    col='Estabelecimento',
    row='T. Categoria',
    kind='bar',
    sharex=False,
    height=4, aspect=1.5,
    palette='viridis'
)

g.set_axis_labels("Quantidade", "Descrição do Produto")
g.set_titles(col_template="{col_name}", row_template="T. Categoria: {row_name}")
g.fig.suptitle('Top 5 Itens por Estabelecimento e Tipo de Categoria', y=1.02, fontsize=16)

plt.tight_layout()
plt.show()

